// Player Stats Data
const playerStats = [
    { name: "Fraser", apps: 33, wins: 14, draws: 2, losses: 17, goals: 58, motm: 5, goalsPerGame: 1.8, winRate: "42%", drawRate: "6%", lossRate: "52%", motmPerGame: 0.15, position: "Forward" },
    { name: "Gus", apps: 36, wins: 16, draws: 5, losses: 15, goals: 28, motm: 2, goalsPerGame: 0.8, winRate: "44%", drawRate: "14%", lossRate: "42%", motmPerGame: 0.06, position: "Forward" },
    { name: "Gid", apps: 25, wins: 13, draws: 3, losses: 9, goals: 27, motm: 4, goalsPerGame: 1.1, winRate: "52%", drawRate: "12%", lossRate: "36%", motmPerGame: 0.16, position: "Forward" },
    { name: "Tom Liv", apps: 34, wins: 15, draws: 4, losses: 15, goals: 23, motm: 1, goalsPerGame: 0.7, winRate: "44%", drawRate: "12%", lossRate: "44%", motmPerGame: 0.03, position: "Forward" },
    { name: "Svi", apps: 12, wins: 6, draws: 2, losses: 4, goals: 16, motm: 0, goalsPerGame: 1.3, winRate: "50%", drawRate: "17%", lossRate: "33%", motmPerGame: 0.00, position: "Forward" },
    { name: "Richard", apps: 12, wins: 5, draws: 1, losses: 6, goals: 15, motm: 0, goalsPerGame: 1.3, winRate: "42%", drawRate: "8%", lossRate: "50%", motmPerGame: 0.00, position: "Forward" },
    { name: "Jake B", apps: 32, wins: 14, draws: 2, losses: 16, goals: 13, motm: 1, goalsPerGame: 0.4, winRate: "44%", drawRate: "6%", lossRate: "50%", motmPerGame: 0.03, position: "Forward" },
    { name: "Miles", apps: 27, wins: 17, draws: 2, losses: 8, goals: 13, motm: 0, goalsPerGame: 0.5, winRate: "63%", drawRate: "7%", lossRate: "30%", motmPerGame: 0.00, position: "Forward" },
    { name: "Malka", apps: 10, wins: 6, draws: 1, losses: 3, goals: 12, motm: 0, goalsPerGame: 1.2, winRate: "60%", drawRate: "10%", lossRate: "30%", motmPerGame: 0.00, position: "Forward" },
    { name: "James R", apps: 17, wins: 7, draws: 1, losses: 9, goals: 11, motm: 1, goalsPerGame: 0.6, winRate: "41%", drawRate: "6%", lossRate: "53%", motmPerGame: 0.06, position: "Midfielder" },
    { name: "Matt R", apps: 41, wins: 17, draws: 4, losses: 20, goals: 10, motm: 7, goalsPerGame: 0.2, winRate: "41%", drawRate: "10%", lossRate: "49%", motmPerGame: 0.17, position: "Midfielder" },
    { name: "Casey", apps: 24, wins: 10, draws: 1, losses: 13, goals: 10, motm: 0, goalsPerGame: 0.4, winRate: "42%", drawRate: "4%", lossRate: "54%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Tom N", apps: 5, wins: 2, draws: 0, losses: 3, goals: 10, motm: 1, goalsPerGame: 2.0, winRate: "40%", drawRate: "0%", lossRate: "60%", motmPerGame: 0.20, position: "Midfielder" },
    { name: "Atticus", apps: 34, wins: 14, draws: 3, losses: 17, goals: 9, motm: 4, goalsPerGame: 0.3, winRate: "41%", drawRate: "9%", lossRate: "50%", motmPerGame: 0.12, position: "Midfielder" },
    { name: "Elan", apps: 27, wins: 13, draws: 3, losses: 11, goals: 9, motm: 0, goalsPerGame: 0.3, winRate: "48%", drawRate: "11%", lossRate: "41%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Eugene", apps: 30, wins: 11, draws: 2, losses: 17, goals: 7, motm: 0, goalsPerGame: 0.2, winRate: "37%", drawRate: "7%", lossRate: "57%", motmPerGame: 0.00, position: "Defender" },
    { name: "Derek", apps: 18, wins: 13, draws: 1, losses: 4, goals: 6, motm: 0, goalsPerGame: 0.3, winRate: "72%", drawRate: "6%", lossRate: "22%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "JM", apps: 8, wins: 5, draws: 2, losses: 1, goals: 6, motm: 0, goalsPerGame: 0.8, winRate: "63%", drawRate: "25%", lossRate: "13%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Bryn", apps: 13, wins: 7, draws: 1, losses: 5, goals: 5, motm: 0, goalsPerGame: 0.4, winRate: "54%", drawRate: "8%", lossRate: "38%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Max", apps: 13, wins: 2, draws: 3, losses: 8, goals: 5, motm: 0, goalsPerGame: 0.4, winRate: "15%", drawRate: "23%", lossRate: "62%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Pran", apps: 6, wins: 2, draws: 0, losses: 4, goals: 5, motm: 0, goalsPerGame: 0.8, winRate: "33%", drawRate: "0%", lossRate: "67%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Xavier", apps: 5, wins: 4, draws: 0, losses: 1, goals: 5, motm: 1, goalsPerGame: 1.0, winRate: "80%", drawRate: "0%", lossRate: "20%", motmPerGame: 0.20, position: "Midfielder" },
    { name: "Jack DC", apps: 11, wins: 6, draws: 1, losses: 4, goals: 4, motm: 0, goalsPerGame: 0.4, winRate: "55%", drawRate: "9%", lossRate: "36%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Simon", apps: 7, wins: 4, draws: 2, losses: 1, goals: 4, motm: 1, goalsPerGame: 0.6, winRate: "57%", drawRate: "29%", lossRate: "14%", motmPerGame: 0.14, position: "Midfielder" },
    { name: "Matt M", apps: 4, wins: 3, draws: 0, losses: 1, goals: 4, motm: 1, goalsPerGame: 1.0, winRate: "75%", drawRate: "0%", lossRate: "25%", motmPerGame: 0.25, position: "Midfielder" },
    { name: "Ty", apps: 4, wins: 2, draws: 0, losses: 2, goals: 4, motm: 0, goalsPerGame: 1.0, winRate: "50%", drawRate: "0%", lossRate: "50%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Bertie", apps: 12, wins: 6, draws: 1, losses: 5, goals: 3, motm: 0, goalsPerGame: 0.3, winRate: "50%", drawRate: "8%", lossRate: "42%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Michael E", apps: 10, wins: 1, draws: 1, losses: 8, goals: 3, motm: 0, goalsPerGame: 0.3, winRate: "10%", drawRate: "10%", lossRate: "80%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Sammy", apps: 9, wins: 3, draws: 2, losses: 4, goals: 3, motm: 0, goalsPerGame: 0.3, winRate: "33%", drawRate: "22%", lossRate: "44%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Huxley", apps: 5, wins: 2, draws: 1, losses: 2, goals: 3, motm: 1, goalsPerGame: 0.6, winRate: "40%", drawRate: "20%", lossRate: "40%", motmPerGame: 0.20, position: "Midfielder" },
    { name: "Hugh", apps: 3, wins: 1, draws: 1, losses: 1, goals: 3, motm: 0, goalsPerGame: 1.0, winRate: "33%", drawRate: "33%", lossRate: "33%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Brad", apps: 22, wins: 12, draws: 1, losses: 9, goals: 2, motm: 1, goalsPerGame: 0.1, winRate: "55%", drawRate: "5%", lossRate: "41%", motmPerGame: 0.05, position: "Midfielder" },
    { name: "Jake L", apps: 17, wins: 8, draws: 2, losses: 7, goals: 2, motm: 0, goalsPerGame: 0.1, winRate: "47%", drawRate: "12%", lossRate: "41%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Danny", apps: 30, wins: 12, draws: 3, losses: 15, goals: 1, motm: 2, goalsPerGame: 0.0, winRate: "40%", drawRate: "10%", lossRate: "50%", motmPerGame: 0.07, position: "Midfielder" },
    { name: "Ollie", apps: 15, wins: 4, draws: 4, losses: 7, goals: 1, motm: 0, goalsPerGame: 0.1, winRate: "27%", drawRate: "27%", lossRate: "47%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Oscar", apps: 10, wins: 8, draws: 1, losses: 1, goals: 1, motm: 2, goalsPerGame: 0.1, winRate: "80%", drawRate: "10%", lossRate: "10%", motmPerGame: 0.20, position: "Midfielder" },
    { name: "Dean", apps: 6, wins: 3, draws: 1, losses: 2, goals: 1, motm: 0, goalsPerGame: 0.2, winRate: "50%", drawRate: "17%", lossRate: "33%", motmPerGame: 0.00, position: "Midfielder" },
    { name: "Fox", apps: 46, wins: 24, draws: 4, losses: 18, goals: 0, motm: 3, goalsPerGame: 0.0, winRate: "52%", drawRate: "9%", lossRate: "39%", motmPerGame: 0.07, position: "Goalkeeper" },
    { name: "Will", apps: 22, wins: 8, draws: 1, losses: 13, goals: 0, motm: 1, goalsPerGame: 0.0, winRate: "36%", drawRate: "5%", lossRate: "59%", motmPerGame: 0.05, position: "Defender" },
    { name: "Lexi", apps: 22, wins: 7, draws: 4, losses: 11, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "32%", drawRate: "18%", lossRate: "50%", motmPerGame: 0.00, position: "Defender" },
    { name: "Tom W", apps: 18, wins: 8, draws: 1, losses: 9, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "44%", drawRate: "6%", lossRate: "50%", motmPerGame: 0.00, position: "Defender" },
    { name: "Freddie", apps: 15, wins: 10, draws: 1, losses: 4, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "67%", drawRate: "7%", lossRate: "27%", motmPerGame: 0.00, position: "Defender" },
    { name: "Tim", apps: 11, wins: 4, draws: 1, losses: 6, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "36%", drawRate: "9%", lossRate: "55%", motmPerGame: 0.00, position: "Defender" },
    { name: "Tony", apps: 11, wins: 1, draws: 1, losses: 9, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "9%", drawRate: "9%", lossRate: "82%", motmPerGame: 0.00, position: "Defender" },
    { name: "Sai", apps: 10, wins: 5, draws: 1, losses: 4, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "50%", drawRate: "10%", lossRate: "40%", motmPerGame: 0.00, position: "Defender" },
    { name: "Steve T", apps: 8, wins: 3, draws: 0, losses: 5, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "38%", drawRate: "0%", lossRate: "63%", motmPerGame: 0.00, position: "Defender" },
    { name: "Ben N", apps: 7, wins: 3, draws: 0, losses: 4, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "43%", drawRate: "0%", lossRate: "57%", motmPerGame: 0.00, position: "Defender" },
    { name: "David Z", apps: 6, wins: 4, draws: 0, losses: 2, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "67%", drawRate: "0%", lossRate: "33%", motmPerGame: 0.00, position: "Defender" },
    { name: "Ed", apps: 6, wins: 4, draws: 0, losses: 2, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "67%", drawRate: "0%", lossRate: "33%", motmPerGame: 0.00, position: "Defender" },
    { name: "Teddy", apps: 6, wins: 3, draws: 0, losses: 3, goals: 0, motm: 1, goalsPerGame: 0.0, winRate: "50%", drawRate: "0%", lossRate: "50%", motmPerGame: 0.17, position: "Defender" },
    { name: "Hugo", apps: 5, wins: 2, draws: 1, losses: 2, goals: 0, motm: 1, goalsPerGame: 0.0, winRate: "40%", drawRate: "20%", lossRate: "40%", motmPerGame: 0.20, position: "Defender" },
    { name: "Frank", apps: 5, wins: 2, draws: 0, losses: 3, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "40%", drawRate: "0%", lossRate: "60%", motmPerGame: 0.00, position: "Defender" },
    { name: "Bello", apps: 4, wins: 2, draws: 0, losses: 2, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "50%", drawRate: "0%", lossRate: "50%", motmPerGame: 0.00, position: "Defender" },
    { name: "Ben W", apps: 4, wins: 2, draws: 1, losses: 1, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "50%", drawRate: "25%", lossRate: "25%", motmPerGame: 0.00, position: "Defender" },
    { name: "Nathan", apps: 4, wins: 2, draws: 0, losses: 2, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "50%", drawRate: "0%", lossRate: "50%", motmPerGame: 0.00, position: "Defender" },
    { name: "Staph", apps: 4, wins: 2, draws: 0, losses: 2, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "50%", drawRate: "0%", lossRate: "50%", motmPerGame: 0.00, position: "Defender" },
    { name: "Andreas", apps: 3, wins: 2, draws: 1, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "67%", drawRate: "33%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Joe", apps: 3, wins: 0, draws: 1, losses: 2, goals: 0, motm: 1, goalsPerGame: 0.0, winRate: "0%", drawRate: "33%", lossRate: "67%", motmPerGame: 0.33, position: "Defender" },
    { name: "James W", apps: 2, wins: 2, draws: 0, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "100%", drawRate: "0%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Adam S", apps: 2, wins: 1, draws: 0, losses: 1, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "50%", drawRate: "0%", lossRate: "50%", motmPerGame: 0.00, position: "Defender" },
    { name: "Iacopo", apps: 2, wins: 1, draws: 0, losses: 1, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "50%", drawRate: "0%", lossRate: "50%", motmPerGame: 0.00, position: "Defender" },
    { name: "Cornell", apps: 2, wins: 0, draws: 0, losses: 2, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "0%", lossRate: "100%", motmPerGame: 0.00, position: "Defender" },
    { name: "BJ", apps: 1, wins: 1, draws: 0, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "100%", drawRate: "0%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Finlay", apps: 1, wins: 1, draws: 0, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "100%", drawRate: "0%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Frankie", apps: 1, wins: 1, draws: 0, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "100%", drawRate: "0%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Gazza", apps: 1, wins: 1, draws: 0, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "100%", drawRate: "0%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Michael C", apps: 1, wins: 1, draws: 0, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "100%", drawRate: "0%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Sean", apps: 1, wins: 1, draws: 0, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "100%", drawRate: "0%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Steve K", apps: 1, wins: 1, draws: 0, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "100%", drawRate: "0%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Adam W", apps: 1, wins: 0, draws: 1, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "100%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Amos", apps: 1, wins: 0, draws: 0, losses: 1, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "0%", lossRate: "100%", motmPerGame: 0.00, position: "Defender" },
    { name: "Cesc", apps: 1, wins: 0, draws: 1, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "100%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "David H", apps: 1, wins: 0, draws: 1, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "100%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Guan", apps: 1, wins: 0, draws: 0, losses: 1, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "0%", lossRate: "100%", motmPerGame: 0.00, position: "Defender" },
    { name: "Hooper", apps: 1, wins: 0, draws: 1, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "100%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Ikki", apps: 1, wins: 0, draws: 0, losses: 1, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "0%", lossRate: "100%", motmPerGame: 0.00, position: "Defender" },
    { name: "Josh H", apps: 1, wins: 0, draws: 1, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "100%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Marc", apps: 1, wins: 0, draws: 1, losses: 0, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "100%", lossRate: "0%", motmPerGame: 0.00, position: "Defender" },
    { name: "Moses", apps: 1, wins: 0, draws: 0, losses: 1, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "0%", lossRate: "100%", motmPerGame: 0.00, position: "Defender" },
    { name: "Rob D", apps: 1, wins: 0, draws: 0, losses: 1, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "0%", lossRate: "100%", motmPerGame: 0.00, position: "Defender" },
    { name: "Tolu", apps: 1, wins: 0, draws: 0, losses: 1, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "0%", lossRate: "100%", motmPerGame: 0.00, position: "Defender" },
    { name: "Tom C", apps: 1, wins: 0, draws: 0, losses: 1, goals: 0, motm: 0, goalsPerGame: 0.0, winRate: "0%", drawRate: "0%", lossRate: "100%", motmPerGame: 0.00, position: "Defender" }
];

// Club-wide fun facts from the dashboard
const clubStats = {
    totalMatches: 50,
    totalGoals: 419,
    goalsPerGame: 8.4,
    whitesWins: 29,
    coloursWins: 16,
    draws: 5,
    uniquePlayers: 82,
    highestScoringGame: "GW25: Whites 11-8 Colours (19 goals!)",
    lowestScoringGame: "GW5 & GW47: 3 goals each",
    biggestWin: "GW1: Whites 11-2 Colours",
    longestWinStreak: "Whites: 7 games (GW16-22)",
    cleanSheets: "Only 1 total! (GW9: Whites 4-0)",
    topScorer: { name: "Fraser", goals: 58, apps: 33 },
    mostMOTMs: { name: "Matt R", motms: 7, apps: 41 },
    ironMan: { name: "Fox", apps: 46, attendance: "92%" },
    bestWinRate: { name: "Oscar", winRate: "80%", record: "8W-1D-1L" },
    worstWinRate: { name: "Tony", winRate: "9%", record: "1W-1D-9L" },
    mostLethal: { name: "Tom N", goalsPerGame: "2.0", record: "10 goals in 5 games" }
};
